# CR: Не знаю як працює Symfony, але на мою думку, краще була б явна регістрація залежностей використовуючи PHP замість неявної в форматі YML, особливо в проекті такого розміру.

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  App\:
    resource: '../src/*'
    exclude:
      - '../src/*/ValueObject/*'
